"""Pydantic request/response schemas for API routes."""
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field

from .state import WEB_SEARCH_AVAILABLE


# ── Token tracking model ─────────────────────────────────────────────────────
class TokenTracking(BaseModel):
    """Granular token usage for every stage of the pipeline."""
    embedding_tokens: int = Field(0, description="Tokens used for query embedding")
    context_tokens: int = Field(0, description="Tokens in retrieved context sent to LLM")
    prompt_tokens: int = Field(0, description="Total input tokens (system + context + history)")
    completion_tokens: int = Field(0, description="Output tokens generated by LLM")
    total_tokens: int = Field(0, description="prompt_tokens + completion_tokens")
    session_total_tokens: int = Field(0, description="Cumulative tokens for the entire session")
    cost_estimate_usd: float = Field(0.0, description="Estimated cost in USD")


class QueryRequest(BaseModel):
    """Request model for single query"""
    query: str = Field(..., description="The user's question")
    top_k: int = Field(5, description="Number of chunks to retrieve", ge=1, le=20)
    min_score: float = Field(0.1, description="Minimum similarity score for chunks", ge=0.0, le=1.0)
    temperature: float = Field(0.0, description="LLM temperature (0.0 for deterministic)", ge=0.0, le=1.0)
    max_tokens: int = Field(500, description="Maximum tokens in response", ge=50, le=4000)
    include_citations: bool = Field(False, description="Include source citations in response")
    include_s3_paths: bool = Field(True, description="Include S3 bucket paths for source documents")
    filter_source_type: Optional[str] = Field(None, description="Filter by source type (drawing/specification/sql)")
    debug: bool = Field(False, description="Include debug information in response")
    project_id: Optional[int] = Field(None, description="Project ID to query")
    session_id: Optional[str] = Field(None, description="Session ID for continuing conversation")
    create_new_session: bool = Field(False, description="Create a new session even if session_id is provided")
    search_mode: str = Field("rag", description="Search mode: 'rag' (default), 'web', or 'hybrid'", pattern="^(rag|web|hybrid)$")


# NEW: Web Search Request Model
class WebSearchRequest(BaseModel):
    """Request model for web search query"""
    query: str = Field(..., description="The user's question for web search")
    temperature: float = Field(0.0, description="LLM temperature", ge=0.0, le=1.0)
    max_tokens: int = Field(1000, description="Maximum tokens in response", ge=50, le=4000)
    session_id: Optional[str] = Field(None, description="Session ID for continuing conversation")
    create_new_session: bool = Field(False, description="Create a new session even if session_id is provided")
    use_conversation_history: bool = Field(True, description="Use conversation history from session if available")


class BatchQueryRequest(BaseModel):
    """Request model for batch queries"""
    queries: List[str] = Field(..., description="List of user questions")
    top_k: int = Field(5, description="Number of chunks to retrieve per query", ge=1, le=20)
    min_score: float = Field(0.1, description="Minimum relevance score for chunks", ge=0.0, le=1.0)
    temperature: float = Field(0.0, description="LLM temperature", ge=0.0, le=1.0)
    max_tokens: int = Field(500, description="Maximum tokens per response", ge=50, le=2000)
    include_citations: bool = Field(False, description="Include source citations in responses")
    project_id: Optional[int] = Field(None, description="Project ID to query")

class ConversationQuery(BaseModel):
    """Request model for conversation with history"""
    query: str = Field(..., description="The user's current question")
    conversation_history: Optional[List[Dict[str, str]]] = Field(
        None, 
        description="Previous conversation messages in OpenAI format"
    )
    top_k: int = Field(5, description="Number of chunks to retrieve", ge=1, le=20)
    min_score: float = Field(0.1, description="Minimum relevance score for chunks", ge=0.0, le=1.0)
    temperature: float = Field(0.0, description="LLM temperature", ge=0.0, le=1.0)
    max_tokens: int = Field(300, description="Maximum tokens in response", ge=50, le=2000)
    filter_source_type: Optional[str] = Field(None, description="Filter by source type")
    project_id: Optional[int] = Field(None, description="Project ID to query")

class RetrievalChunk(BaseModel):
    """A single retrieved context chunk from the FAISS index."""
    index:         int
    text:          str
    source_type:   str
    similarity:    float
    distance:      float
    token_count:   int
    drawing_id:    Optional[Union[str, int]] = None
    pdf_name:      Optional[str]             = None
    s3_path:       Optional[str]             = None
    page:          Optional[int]             = None
    set_id:        Optional[Union[str, int]] = None
    trade_id:      Optional[Union[str, int]] = None
    drawing_name:  Optional[str]             = None
    drawing_title: Optional[str]             = None   # raw field from metadata
    display_title: Optional[str]             = None   # best human-readable title
    download_url:  Optional[str]             = None   # clickable HTTPS link
    trade_name:    Optional[str]             = None
    set_name:      Optional[str]             = None
    set_trade:     Optional[str]             = None
    material:      Optional[str]             = None
    quantity:      Optional[str]             = None
    unit:          Optional[str]             = None
    created_at:    Optional[str]             = None

# Updated SourceDocument model to match requested schema
class SourceDocument(BaseModel):
    """Source document with human-readable title and clickable download link."""
    s3_path:       str
    file_name:     str           = Field(..., description="Raw file name from metadata")
    display_title: Optional[str] = Field(None, description="Human-readable drawing title (drawing_title or fallback)")
    download_url:  Optional[str] = Field(None, description="Clickable HTTPS download link to the PDF")

class QueryResponse(BaseModel):
    """Response model for single query"""
    query: str
    answer: Optional[str] = Field(
        None,
        description=(
            "Combined answer (rag + web). Populated in 'rag' and 'web' modes. "
            "null in 'hybrid' mode — use rag_answer and web_answer instead."
        ),
    )
    rag_answer: Optional[str] = Field(
        None,
        description=(
            "Answer derived solely from project documents (RAG). "
            "Populated in 'rag' and 'hybrid' modes. "
            "Contains 'not found' message when documents have no relevant content."
        ),
    )
    web_answer: Optional[str] = Field(
        None,
        description=(
            "Answer derived solely from web search. "
            "Populated in 'web' and 'hybrid' modes. "
            "Contains the raw OpenAI web-search answer (no project docs used)."
        ),
    )
    retrieval_count: int
    average_score: float
    confidence_score: float = Field(0.0, description="Confidence score 0-1 based on retrieval quality")
    is_clarification: bool = Field(False, description="True if answer is a clarification request due to low confidence")
    follow_up_questions: List[str] = Field(default_factory=list, description="3 suggested follow-up questions")
    model_used: str
    token_usage: Optional[Dict[str, int]] = None
    token_tracking: Optional[TokenTracking] = Field(None, description="Granular token tracking")
    s3_paths: List[str] = Field(default_factory=list, description="Unique S3 bucket paths")
    s3_path_count: int = Field(0, description="Number of unique S3 paths")
    source_documents: List[SourceDocument] = Field(default_factory=list, description="Structured source document information")
    retrieved_chunks: List[RetrievalChunk] = Field(default_factory=list, description="Retrieved context chunks")
    debug_info: Optional[Dict[str, Any]] = None
    processing_time_ms: int = Field(0, description="Total processing time in milliseconds")
    project_id: Optional[int] = Field(None, description="Project ID queried")
    session_id: Optional[str] = Field(None, description="Session ID for continuing conversation")
    session_stats: Optional[Dict[str, Any]] = Field(None, description="Session statistics")
    search_mode: str = Field("rag", description="Search mode used: rag, web, or hybrid")
    web_sources: List[Dict[str, str]] = Field(default_factory=list, description="Web sources with title and URL")
    web_source_count: int = Field(0, description="Number of web sources")

# NEW: Web Search Response Model
class WebSearchResponse(BaseModel):
    """Response model for web search query"""
    query: str
    answer: str
    sources: List[Dict[str, str]] = Field(default_factory=list, description="Web sources with title and URL")
    source_count: int = Field(0, description="Number of web sources")
    model_used: str
    token_usage: Optional[Dict[str, int]] = None
    processing_time_ms: int = Field(0, description="Total processing time in milliseconds")
    # Session information
    session_id: Optional[str] = Field(None, description="Session ID for continuing conversation")
    session_stats: Optional[Dict[str, Any]] = Field(None, description="Session statistics")
    web_search_available: bool = Field(True, description="Whether web search was available")


class SessionCreateRequest(BaseModel):
    """Request to create a new session"""
    initial_query: Optional[str] = Field(None, description="Initial query for the session")
    project_id: Optional[int] = Field(None, description="Project ID")
    filter_source_type: Optional[str] = Field(None, description="Filter by source type")
    custom_instructions: Optional[str] = Field(None, description="Custom instructions for the session")

class SessionUpdateRequest(BaseModel):
    """Request to update session context"""
    project_id: Optional[int] = Field(None, description="Project ID")
    filter_source_type: Optional[str] = Field(None, description="Filter by source type")
    custom_instructions: Optional[str] = Field(None, description="Custom instructions")


class BatchResponseItem(BaseModel):
    """Response model for individual query in batch"""
    query: str
    answer: str
    retrieval_count: int
    average_score: float
    success: bool
    error: Optional[str] = None
    processing_time_ms: int = 0
    project_id: Optional[int] = None

class BatchQueryResponse(BaseModel):
    """Response model for batch queries"""
    total_queries: int
    successful: int
    failed: int
    results: List[BatchResponseItem]
    total_processing_time_ms: int
    project_id: Optional[int] = None

class HealthResponse(BaseModel):
    """Health check response"""
    status:               str
    model:                str
    retrieval_available:  bool
    web_search_available: bool           = False
    web_search_enabled:   bool           = WEB_SEARCH_AVAILABLE
    openai_available:     bool
    memory_available:     bool           = False
    active_sessions:      int            = 0
    index_vectors:        int            = 0
    metadata_records:     int            = 0
    timestamp:            str            = ""
    version:              str            = "1.3.0"
    project_id:           Optional[int]  = None
